### ISSUE TITLE
Storing state / default settings in .vscode/settings.json

### ISSUE THREAD

**Issue by dopry** [AngularDoc/angulardoc.github.io#5]
I noticed angular doc has started modifying my .vscode/settings.json on all of my projects. As a team we use VS Code and share our settings via git. I'd much rather it didn't alter our settings.json.  None of the other extensions we use do this.

**Comment by agiledigits** [comment]
We used to have our own config file in .vscode/angulardoc.json, but a few releases later VS Code stopped treating it as one of the setting files and our extension wouldn't get the file change notification any more.

**Comment by dopry** [comment]
I saw that change, but currently you're writing default values into the config file that could stay in your extension.

out of 
```
{
    "angulardoc.repoId": "********-****-****-*************",
    "angulardoc.directoryFilter": [
        "!typings",
        "!node_modules",
        "!.vscode"
    ],
    "angulardoc.fileFilter": [
        "**/!(*.*spec).ts"
    ],
    "angulardoc.lastSync": 0
}
````

**Comment by mlc-mlapis** [comment]
@agiledigits We also have a problem with changes in `settings.json` because it is the file that is included in GitHub repo = sharing our team project's setting. It is really necessary to find a different place to store the extension config data.

**Comment by mlc-mlapis** [comment]
Is there someting new? The fact that `settings.json` is used for storing is really a serious problem. In reality it is very difficult to use AngularDoc with this behaviour ... if there are more devs on the project than one!!!

**Comment by agiledigits** [comment]
@mlc-mlapis We are actively working on a new solution which I believe will provide a superior user experience and richer features. Please stay tuned.

**Comment by mlc-mlapis** [comment]
Thanks a lot for any solution, even temporary.

**Comment by agiledigits** [comment]
We have published v2.2.0 which moved the angulardoc settings from "settings.json" to the restored "angulardoc.json" file. Please try it and let us know what happens.

**Comment by mlc-mlapis** [comment]
Thanks for news but I am a bit lost. I uninstall, reinstall ... AngularDoc ext several times but nothing runs in the end. Nothing as `AngularDoc` on the status bar.

If I try to invoke `ngdoc` the a message `command 'ngdoc' not found` appears.

I have VSC 1.12.2 on Windows 8.1 and AngularDoc 2.2.0 installed. So there is certainly a problem.

I have params in my personal `settings.json` file as:
```
...
"angulardoc.email": "xxx@xxx.xx",
"angulardoc.access_token": "",
"angulardoc.username": "xxx@xxx.xx",
"angulardoc.directoryFilter": [
	"!typings",
	"!node_modules",
	"!.vscode"
],
"angulardoc.fileFilter": [
	"**/!(*.*spec).ts"
],
...
```

**Comment by agiledigits** [comment]
I sounds like the extension wasn't activated. The first thing I'd check is whether there's package.json file in the root directory as we won't activate the extension for non-angular projects.

**Comment by mlc-mlapis** [comment]
Hmmm, it is here for sure. But from this point of view, Angular 4.2.0-beta.1 is installed. Do you think that this is the problem?

**Comment by agiledigits** [comment]
We look for "@angular/core" in dependencies.

**Comment by mlc-mlapis** [comment]
Hmmm, I have the following, so that looks enough ...
```
...
"dependencies": {
	"systemjs": "0.20.12",
	"core-js": "2.4.1",
	"reflect-metadata": "0.1.10",
	"rxjs": "5.4.0",
	"zone.js": "0.8.10",
	"@angular/core": "4.2.0-beta.1",
	"@angular/common": "4.2.0-beta.1",
	"@angular/compiler": "4.2.0-beta.1",
	"@angular/compiler-cli": "4.2.0-beta.1",
	"@angular/platform-server": "4.2.0-beta.1",
	"@angular/platform-browser": "4.2.0-beta.1",
	"@angular/platform-browser-dynamic": "4.2.0-beta.1",
	"@angular/platform-webworker": "4.2.0-beta.1",
	"@angular/platform-webworker-dynamic": "4.2.0-beta.1",
	"@angular/language-service": "4.2.0-beta.1",
	"@angular/http": "4.2.0-beta.1",
	"@angular/forms": "4.2.0-beta.1",
	"@angular/router": "4.2.0-beta.1",
	"@angular/animations": "4.2.0-beta.1",
	"@ngrx/core": "1.2.0",
	"@ngrx/store": "2.2.2",
	"primeng": "4.0.0",
	"raven-js": "3.15.0",
	"runtime-type-checks": "0.0.4"
},
...
```

**Comment by agiledigits** [comment]
Could it be that you don't have tsconfig.json or angular-cli.json files? We made a small patch to deal with that situation.

**Comment by mlc-mlapis** [comment]
Thanks. I tried to install version 2.2.1. But nothing changed. Still any using of `ngdoc` or any of `ng g ....` ends with a warning`command 'ngdoc' not found` or `command 'ng.xxx' not found`. So the small patch doesn't have any effect. It has to be probably something else.

I have `tsconfig.json` file ... as it is working Angular's project (even previously it was) based on using SystemJS. I have installed also Angular CLI globally but the project is not CLI project so I don't have `angular-cli.json`. But I didn't have it before also and AngularDoc has been working (2.1.0).

I checked and `xxx\.vscode\extensions\AngularDoc.angulardoc-vscode-2.2.1` exists in a user directory.

**Comment by agiledigits** [comment]
Any chance you are not using the latest VS Code?

**Comment by mlc-mlapis** [comment]
No, I am using the latest VSC: 1.12.2

I tried the same ^^ on the second PC where Windows 10 is install and the same project repository. The behavior is exactly the same. So the problem has to be a general one. I can't see any message, just nothing.

**Comment by dopry** [comment]
I am using VSC 1.12.2 w/AngularDoc 2.2.1 with Node 7.4.

The generate commands are in my context menu, but do nothing. I don't have an icon to open the docs. If I try to run ngdoc from the command palette, i get the error message "command 'ngdoc' not found".

**Comment by mlc-mlapis** [comment]
@dopry ... so exactly the same, I think.

**Comment by agiledigits** [comment]
Could it be that you have multiple node_modules where package.json files are found? If so, please try v2.2.2 that we just released.

**Comment by mlc-mlapis** [comment]
@agiledigits How do you mean that? The directory `node_modules` in the project root contains other modules ... nested and each of them contains also `package.json` file but it is normal, isn't it?

I tried to install version 2.2.2 but there is no difference. Still the same situation as with previous versions.

**Comment by agiledigits** [comment]
There was a chance that we might be looking in the wrong package.json file for the angular dependencies. However the patch didn't fix your issue, and I'm running out of ideas. Perhaps you can try the sample repo https://github.com/mgechev/angular-seed/ and see if it works.
